version: "3"
services:
  app:
    env_file:
      - .env
    build: .
    depends_on:
      - postgres
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOSTNAME: ${DB_CONTAINER}
      DB_PORT: ${DB_PORT}
      NODE_ENV: dev
      PORT: 5000
    ports:
      - "5000:5000"
    command: yarn dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    env_file:
      - .env
    image: postgres:13.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
